const app=document.querySelector("#app"),nav=document.querySelector("#bottomNav"),toastEl=document.querySelector("#toast");
const KEY="booknotes-state-v2";let state=JSON.parse(localStorage.getItem(KEY)||'{"favorites":[],"completed":[],"notes":{}}');
if(!state.library) state.library=JSON.parse(JSON.stringify(window.BOOKS||[]));
// Import newly published books into existing on-device libraries without overwriting user edits.
for(const incoming of (window.BOOKS||[])) {
  const existing=state.library.find(book=>book.id===incoming.id);
  if(!existing) state.library.push(JSON.parse(JSON.stringify(incoming)));
  else {
    if(!Array.isArray(existing.chapters)) existing.chapters=[];
    for(const chapter of (incoming.chapters||[])) {
      if(!existing.chapters.some(saved=>saved.id===chapter.id)) existing.chapters.push(JSON.parse(JSON.stringify(chapter)));
    }
  }
}
// Add newly published chapters to existing on-device books, preserving local edits and notes.
for(const incoming of (window.BOOKS||[])) {
  const existing=state.library.find(book=>book.id===incoming.id);
  if(existing) for(const chapter of (incoming.chapters||[])) {
    if(!existing.chapters.some(c=>c.id===chapter.id)) existing.chapters.push(JSON.parse(JSON.stringify(chapter)));
  }
}
// Hide the untouched starter example when the first real book is published.
state.library=state.library.filter(book=>book.id!=="demo-book" || book.title!=="Первая книга" || book.author!=="Добавим твою книгу" || book.chapters.length!==1 || book.chapters[0].title!=="Первая глава");
localStorage.setItem(KEY,JSON.stringify(state));
let books=state.library;
const save=()=>{state.library=books;localStorage.setItem(KEY,JSON.stringify(state))};const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const key=(b,c)=>b+"/"+c;function toast(t){toastEl.textContent=t;toastEl.classList.add("show");setTimeout(()=>toastEl.classList.remove("show"),1800)}
function header(back){return '<header class="topbar">'+(back?'<a class="icon-btn" href="'+back+'">←</a>':'<div class="brand-mark">B</div>')+'<div class="brand">BookNotes</div></header>'}
function bottom(active="library"){nav.innerHTML='<a class="'+(active==="library"?"active":"")+'" href="#"><span>⌂</span>Библиотека</a><a class="'+(active==="saved"?"active":"")+'" href="#saved"><span>♡</span>Избранное</a>';nav.style.display="flex"}
function chapterWord(n){let a=n%10,b=n%100;return a===1&&b!==11?"глава":[2,3,4].includes(a)&&![12,13,14].includes(b)?"главы":"глав"}
function cover(book,cls="cover"){return '<div class="'+cls+'" style="--accent:'+(book.accent||"#ded6ca")+'"><div class="cover-rule"></div><div class="cover-symbol">'+esc(book.symbol||"B")+'</div><div class="cover-lines"><span></span><span></span><span></span></div></div>'}
function bookCard(book){return '<a class="book-card" href="#book/'+book.id+'">'+cover(book)+'<div class="book-meta"><p>'+esc(book.category||"Книга")+'</p><h3>'+esc(book.title)+'</h3><span>'+esc(book.author)+'</span><div class="book-foot"><span>'+book.chapters.length+" "+chapterWord(book.chapters.length)+'</span></div></div></a>'}
function libraryStats(){let total=books.reduce((n,b)=>n+b.chapters.length,0),done=state.completed.length,notes=Object.values(state.notes||{}).filter(x=>x&&x.trim()).length;return{total,done,notes}}
function continueItem(){if(state.lastOpened){let [bid,cid]=state.lastOpened.split("/"),b=books.find(x=>x.id===bid),c=b?.chapters.find(x=>x.id===cid);if(b&&c&&!state.completed.includes(state.lastOpened))return{b,c}}for(let b of books){let c=b.chapters.find(x=>!state.completed.includes(key(b.id,x.id)));if(c)return{b,c}}return null}
function renderLibrary(){bottom("library");let stats=libraryStats(),cont=continueItem();app.innerHTML='<div class="shell">'+header()+'<section class="hero"><p class="eyebrow">ЛИЧНАЯ БИБЛИОТЕКА</p><h1>Книги, которые<br><em>остаются с тобой.</em></h1><p class="lead">Короткие конспекты, важные идеи и мысли из каждой прочитанной главы.</p><div class="book-line"><span></span><i></i><span></span></div></section><section class="dashboard"><div class="stat"><b>'+stats.done+'</b><span>глав прочитано</span></div><div class="stat"><b>'+stats.notes+'</b><span>личных заметок</span></div><div class="stat"><b>'+stats.total+'</b><span>глав в библиотеке</span></div></section>'+(cont?'<a class="continue-card" href="#chapter/'+cont.b.id+'/'+cont.c.id+'"><div><span class="eyebrow">ПРОДОЛЖИТЬ</span><h2>'+esc(cont.c.title)+'</h2><p>'+esc(cont.b.title)+' · глава '+cont.c.number+'</p></div><b>→</b></a>':'')+'<section class="section"><div class="library-tools"><div class="section-head"><h2>Мои книги</h2><span class="count">'+books.length+'</span></div><label class="search"><span>⌕</span><input id="search" placeholder="Найти книгу или автора"></label></div><div id="bookGrid" class="books-grid">'+books.map(bookCard).join("")+'</div></section><footer>BookNotes <span>•</span> моя библиотека знаний</footer></div>';document.querySelector("#search").addEventListener("input",e=>{let q=e.target.value.toLowerCase().trim(),x=books.filter(b=>(b.title+" "+b.author).toLowerCase().includes(q));document.querySelector("#bookGrid").innerHTML=x.length?x.map(bookCard).join(""):'<div class="empty">Ничего не найдено.<small>Попробуй другой запрос.</small></div>'})}
function renderBook(id){let b=books.find(x=>x.id===id);if(!b)return renderLibrary();bottom("library");app.innerHTML='<div class="shell">'+header("#")+'<section class="book-hero">'+cover(b,"mini-cover")+'<div class="book-title"><p class="eyebrow">'+esc(b.category||"КНИГА")+'</p><h1>'+esc(b.title)+'</h1><p class="author">'+esc(b.author)+'</p><div class="more-wrap"><button class="more-btn" id="bookMore" aria-label="Действия с книгой">•••</button><div class="more-menu" id="bookMenu"><button id="editBook">✎ Редактировать книгу</button><button id="deleteBook" class="danger">Удалить книгу</button></div></div></div></section><section class="section chapters-section"><div class="section-head"><h2>Главы</h2><span class="count">'+b.chapters.length+'</span></div><div class="chapter-list">'+b.chapters.map(c=>{let done=state.completed.includes(key(b.id,c.id)),fav=state.favorites.includes(key(b.id,c.id));return '<a class="chapter-row '+(done?"done":"")+'" href="#chapter/'+b.id+'/'+c.id+'"><span class="chapter-number">'+String(c.number).padStart(2,"0")+'</span><div><div class="chapter-title-line"><h3>'+esc(c.title)+'</h3>'+(fav?'<span class="tiny-heart">♥</span>':'')+'</div><p>'+esc(c.summary)+'</p></div><span class="status">'+(done?"✓":"→")+'</span></a>'}).join("")+'</div></section></div>';
document.querySelector(".book-hero .more-wrap")?.remove();document.querySelector(".topbar").insertAdjacentHTML("beforeend", '<div class="more-wrap header-more"><button class="more-btn" id="bookMore" aria-label="Действия с книгой">•••</button><div class="more-menu" id="bookMenu"><button id="editBook">✎ Редактировать книгу</button><button id="deleteBook" class="danger">Удалить книгу</button></div></div>');
document.querySelector("#bookMore").onclick=e=>{e.stopPropagation();document.querySelector("#bookMenu").classList.toggle("open")};
document.querySelector("#editBook").onclick=()=>{let title=prompt("Название книги",b.title);if(title===null)return;let author=prompt("Автор",b.author);if(author===null)return;let category=prompt("Категория",b.category||"Книга");if(category===null)return;b.title=title.trim()||b.title;b.author=author.trim()||b.author;b.category=category.trim()||b.category;save();renderBook(id);toast("Книга обновлена")};
document.querySelector("#deleteBook").onclick=()=>{if(!confirm("Удалить книгу «"+b.title+"» и все её главы?"))return;let prefix=b.id+"/";books=books.filter(x=>x.id!==b.id);state.favorites=state.favorites.filter(x=>!x.startsWith(prefix));state.completed=state.completed.filter(x=>!x.startsWith(prefix));Object.keys(state.notes||{}).forEach(k=>{if(k.startsWith(prefix))delete state.notes[k]});if(state.lastOpened?.startsWith(prefix))delete state.lastOpened;save();location.hash="";renderLibrary();toast("Книга удалена")};
scrollTo(0,0)}
function renderChapter(bid,cid){let b=books.find(x=>x.id===bid),c=b?.chapters.find(x=>x.id===cid);if(!b||!c)return renderLibrary();nav.style.display="none";let k=key(bid,cid),fav=state.favorites.includes(k),done=state.completed.includes(k),note=state.notes[k]||"",idx=b.chapters.findIndex(x=>x.id===cid),prev=b.chapters[idx-1],next=b.chapters[idx+1];state.lastOpened=k;save();app.innerHTML='<div class="shell reading-shell">'+header("#book/"+b.id)+'<article class="note"><div class="note-head"><p class="eyebrow">'+esc(b.title)+' · ГЛАВА '+c.number+'</p><h1>'+esc(c.title)+'</h1><p class="read-time">☕ '+esc(c.readTime||"несколько минут")+'</p><div class="chapter-actions"><button id="fav">'+(fav?"♥ В избранном":"♡ В избранное")+'</button><button id="done">'+(done?"✓ Прочитано":"○ Отметить прочитанной")+'</button><div class="more-wrap chapter-more"><button class="more-btn" id="chapterMore" aria-label="Действия с главой">•••</button><div class="more-menu" id="chapterMenu"><button id="editChapter">✎ Редактировать главу</button><button id="deleteChapter" class="danger">Удалить главу</button></div></div></div></div><section class="note-block intro"><span class="ornament">✦</span><p>'+esc(c.summary)+'</p></section><section class="note-block"><p class="block-label">ГЛАВНЫЕ ИДЕИ</p><div class="ideas">'+c.ideas.map((x,i)=>'<div class="idea"><b>'+String(i+1).padStart(2,"0")+'</b><p>'+esc(x)+'</p></div>').join("")+'</div></section><section class="quote-card"><span>ЗАПОМНИТЬ</span><p>'+esc(c.takeaway)+'</p></section><section class="apply-card"><div class="apply-icon">↗</div><div><span>ПРИМЕНИТЬ</span><p>'+esc(c.apply)+'</p></div></section><section class="personal-note"><div><span>МОЯ ЗАМЕТКА</span><small>Сохраняется только на этом устройстве</small></div><textarea id="personalNote" placeholder="Запиши свою мысль по этой главе…">'+esc(note)+'</textarea><button id="saveNote">Сохранить заметку</button></section><nav class="chapter-nav">'+(prev?'<a href="#chapter/'+b.id+'/'+prev.id+'"><small>← ПРЕДЫДУЩАЯ</small><span>'+esc(prev.title)+'</span></a>':'<i></i>')+(next?'<a class="next" href="#chapter/'+b.id+'/'+next.id+'"><small>СЛЕДУЮЩАЯ →</small><span>'+esc(next.title)+'</span></a>':'<a class="next finish" href="#book/'+b.id+'"><small>КНИГА</small><span>Все главы пройдены ✦</span></a>')+'</nav></article></div>';document.querySelector("#fav").onclick=()=>{state.favorites=state.favorites.includes(k)?state.favorites.filter(x=>x!==k):[...state.favorites,k];save();renderChapter(bid,cid);toast(state.favorites.includes(k)?"Добавлено в избранное":"Удалено из избранного")};document.querySelector("#done").onclick=()=>{state.completed=state.completed.includes(k)?state.completed.filter(x=>x!==k):[...state.completed,k];save();renderChapter(bid,cid);toast(state.completed.includes(k)?"Глава прочитана ✓":"Отметка снята")};document.querySelector("#saveNote").onclick=()=>{state.notes[k]=document.querySelector("#personalNote").value;save();toast("Заметка сохранена")};
document.querySelector(".chapter-actions .chapter-more")?.remove();document.querySelector(".topbar").insertAdjacentHTML("beforeend", '<div class="more-wrap header-more"><button class="more-btn" id="chapterMore" aria-label="Действия с главой">•••</button><div class="more-menu" id="chapterMenu"><button id="editChapter">✎ Редактировать главу</button><button id="deleteChapter" class="danger">Удалить главу</button></div></div>');
document.querySelector("#chapterMore").onclick=e=>{e.stopPropagation();document.querySelector("#chapterMenu").classList.toggle("open")};
document.querySelector("#editChapter").onclick=()=>{let title=prompt("Название главы",c.title);if(title===null)return;let summary=prompt("Краткий конспект",c.summary||"");if(summary===null)return;let takeaway=prompt("Что запомнить",c.takeaway||"");if(takeaway===null)return;let apply=prompt("Как применить",c.apply||"");if(apply===null)return;c.title=title.trim()||c.title;c.summary=summary;c.takeaway=takeaway;c.apply=apply;save();renderChapter(bid,cid);toast("Глава обновлена")};
document.querySelector("#deleteChapter").onclick=()=>{if(!confirm("Удалить главу «"+c.title+"»?"))return;b.chapters=b.chapters.filter(x=>x.id!==c.id);b.chapters.forEach((x,i)=>x.number=i+1);state.favorites=state.favorites.filter(x=>x!==k);state.completed=state.completed.filter(x=>x!==k);delete state.notes[k];if(state.lastOpened===k)delete state.lastOpened;save();location.hash="book/"+b.id;renderBook(b.id);toast("Глава удалена")};
scrollTo(0,0)}
function renderSaved(){bottom("saved");let items=[];books.forEach(b=>b.chapters.forEach(c=>{if(state.favorites.includes(key(b.id,c.id)))items.push({b,c})}));app.innerHTML='<div class="shell">'+header("#")+'<section class="saved-head"><p class="eyebrow">СОХРАНЁННОЕ</p><h1>Избранные главы</h1><p>Самые важные мысли всегда под рукой.</p></section><section class="section"><div class="chapter-list">'+(items.length?items.map(({b,c})=>'<a class="chapter-row" href="#chapter/'+b.id+'/'+c.id+'"><span class="chapter-number">♥</span><div><h3>'+esc(c.title)+'</h3><p>'+esc(b.title)+' · '+esc(c.summary)+'</p></div><span class="status">→</span></a>').join(""):'<div class="empty big">Пока пусто.<small>Нажми «♡ В избранное» внутри нужной главы.</small></div>')+'</div></section></div>'}
function animatePage(){requestAnimationFrame(()=>app.classList.add("page-in"));setTimeout(()=>app.classList.remove("page-in"),520)}
function addRipple(e){let el=e.target.closest("a,button");if(!el)return;let r=el.getBoundingClientRect(),s=document.createElement("span");s.className="ripple";let size=Math.max(r.width,r.height);s.style.width=s.style.height=size+"px";s.style.left=(e.clientX-r.left-size/2)+"px";s.style.top=(e.clientY-r.top-size/2)+"px";el.appendChild(s);setTimeout(()=>s.remove(),600)}
document.addEventListener("pointerdown",addRipple);
function route(){let h=location.hash.slice(1),p=h.split("/");if(p[0]==="book")renderBook(p[1]);else if(p[0]==="chapter")renderChapter(p[1],p[2]);else if(p[0]==="saved")renderSaved();else renderLibrary();animatePage()}
addEventListener("hashchange",route);if("serviceWorker" in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister()));caches.keys().then(keys=>keys.forEach(k=>caches.delete(k)))}route();